title: "Damone Washington - Portfolio"
email: "dwashington124@rams.wssu.edu"
description: "AI Researcher &amp; Software Developer - NC-LSAMP Student Researcher - WSSU Class of 2027"
baseurl: ""
url: "https://Damone-Washington19.github.io"
theme: jekyll-theme-tactile
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  projects:
    output: true